// export const SET_TOKEN = 'SET_TOKEN' // token
export const MENU_LIST = 'MENU_LIST'
export const ORDER_STATUS = 'ORDER_STATUS' // 开单状态 接车 ---结算
export const STORE_STATUS = 'STORE_STATUS' // 商品库状态 服务、商品
export const ADD_SHOP_CAR = 'ADD_SHOP_CAR' // 添加购物车
export const CUT_SHOP_CAR = 'CUT_SHOP_CAR' // 减购物车
export const DEL_SHOP_CAR = 'DEL_SHOP_CAR' // 删除购物车某项
// export const GOODS_UNIT_MAP = 'GOODS_UNIT_MAP' // 商品单位数据字典
export const ORDER_OF_CUSTOM = 'ORDER_OF_CUSTOM' // 当前开单的客户
export const ORDER_OF_CAR = 'ORDER_OF_CAR' // 当前开单的车
export const NEW_CUSTOM_TEL = 'NEW_CUSTOM_TEL' // 搜索新客户的手机号
export const REFRESH = 'REFRESH' // 刷新
export const CLEAR_SHOP_CAR = 'CLEAR_SHOP_CAR' // 清空购物车
export const SET_STORE_STAFF = 'SET_STORE_STAFF' // 店铺员工
export const SHOP_CAR_SG = 'SHOP_CAR_SG' // 施工
// export const SHOP_CAR_LL = 'SHOP_CAR_LL' // 领料
export const PUSH_SHOP_CAR = 'PUSH_SHOP_CAR' // 领料
export const SET_ORDER_ID = 'SET_ORDER_ID' // 设置订单id
export const SET_RECEPTION_ID = 'SET_RECEPTION_ID' // 设置接车id
export const NEW_CUSTOM_CAR = 'NEW_CUSTOM_CAR' // 设置接车id
export const SET_ORDER_INFO = 'SET_ORDER_INFO' // 订单信息 包含接车信息和基本信息
export const CLEAR_ORDER_INFO = 'CLEAR_ORDER_INFO' // 清空订单基本信息 再结算和完工后
export const CLEAR_ORDER_CUSTOM = 'CLEAR_ORDER_CUSTOM' // 清空当前用户
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD' // 当前划卡的卡信息
export const CLEAR_CURRENT_CARD = 'CLEAR_CURRENT_CARD' // 清空当前卡的卡信息
export const CLEAR_STAFF_SL = 'CLEAR_STAFF_SL' // 清空施工人和领料人
export const SET_ACCOUNT_LIST = 'SET_ACCOUNT_LIST' // 设置店铺收款账户
export const SET_ACCOUNT_DEFAULT = 'SET_ACCOUNT_DEFAULT' // 设置默认账户
export const SET_MESSAGES = 'SET_MESSAGES' // 消息
export const SMS_USABLE = 'SMS_USABLE' // 短信余量
export const CURRENT_USER = 'CURRENT_USER' // 设置当前登陆者信息
export const SET_MENU_NAV = 'SET_MENU_NAV' // 设置当前登陆者菜单权限
export const SET_SKU_LIST_CARD = 'SET_SKU_LIST_CARD' // 新增卡添加的sku
export const DEL_SKU_CARD = 'DEL_SKU_CARD' // 删除折扣卡指定index的sku
export const CLEAR_SKU_CARD = 'CLEAR_SKU_CARD' // 清空折扣卡的sku
export const SET_CARD_TYPE = 'SET_CARD_TYPE' // 设置卡的类型
export const ADD_SKU_LIST_CARD = 'ADD_SKU_LIST_CARD' // 次卡添加sku
export const CUT_SKU_LIST_CARD = 'CUT_SKU_LIST_CARD' // 次卡减少sku
export const NOLIMIT_SKU_LIST_CARD = 'NOLIMIT_SKU_LIST_CARD' // 次卡不限
export const PUSH_SKU_LIST_CARD = 'PUSH_SKU_LIST_CARD' // 次卡第一次添加
export const SETONCE_SKU_LIST_CARD = 'SETONCE_SKU_LIST_CARD' // 一次设置卡的sku
export const SET_ACCOUNT_CUS = 'SET_ACCOUNT_CUS' // 设置客户的储值账户
export const NATIVE_PAY_SYS_OK = 'NATIVE_PAY_SYS_OK' // 设置客户的储值账户
export const NATIVE_PAY_SMS_OK = 'NATIVE_PAY_SMS_OK' // 设置客户的储值账户
export const SET_PRODUCT = 'SET_PRODUCT' // 设置客户的储值账户
export const IS_EXP = 'IS_EXP' // 设置客户的储值账户
export const UNAUTH_MENU = 'UNAUTH_MENU' // 设置客户的储值账户
export const SER_REFRESH = 'SER_REFRESH' // 设置客户的储值账户
export const SET_BRAND = 'SET_BRAND' // 设置客户的储值账户
export const CLEAR_BRAND = 'CLEAR_BRAND' // 设置客户的储值账户
export const NATIVE_PIC_UPLOAD_OK = 'NATIVE_PIC_UPLOAD_OK' // 设置客户的储值账户
export const NATIVE_PIC_DEL = 'NATIVE_PIC_DEL' // 设置客户的储值账户
export const NATIVE_PIC_UPLOAD_OK_ORDER = 'NATIVE_PIC_UPLOAD_OK_ORDER' // 设置客户的储值账户
export const NATIVE_PIC_DEL_ORDER = 'NATIVE_PIC_DEL_ORDER' // 设置客户的储值账户
export const SET_NATIVE_PIC_ORDER = 'SET_NATIVE_PIC_ORDER' // 设置客户的储值账户
export const CLEAR_NATIVE_PIC_ORDER = 'CLEAR_NATIVE_PIC_ORDER' // 设置客户的储值账户
export const CLEAR_ORDER_DATA = 'CLEAR_ORDER_DATA' // 清空快单订单中的默认数据
export const SET_NATIVE_PIC = 'SET_NATIVE_PIC' // 清空快单订单中的默认数据
